[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/checkin"
  to = "/sopo-studio/checkin.html"
  status = 302

[[redirects]]
  from = "/book"
  to = "/sopo-studio/book_meeting.html"
  status = 302

[[redirects]]
  from = "/sopo"
  to = "/sopo-studio/index.html"
  status = 302
