[build]
  publish = "."

[[redirects]]
  from = "/checkin"
  to = "/sopo-studio/checkin.html"
  status = 302

[[redirects]]
  from = "/book"
  to = "/sopo-studio/book_meeting.html"
  status = 302

[[redirects]]
  from = "/sopo"
  to = "/sopo-studio/index.html"
  status = 302

[[redirects]]
  from = "/paddy"
  to = "/paddy-studio/index.html"
  status = 302

[[redirects]]
  from = "/paddy-checkin"
  to = "/paddy-studio/checkin.html"
  status = 302

[[redirects]]
  from = "/paddy-book"
  to = "/paddy-studio/book_meeting.html"
  status = 302

[[redirects]]
  from = "/paddy-debrief"
  to = "/paddy-studio/debrief.html"
  status = 302

[[redirects]]
  from = "/paddy-onboarding"
  to = "/paddy-studio/onboarding.html"
  status = 302
